### ISSUE TITLE
Invalid ServiceAccount name when using named releases

### ISSUE THREAD

**Issue by 0x0013** [borchero/switchboard-chart#2]
Hi,

The chart creates a serviceaccount object based on `{{ .Release.Name }}`, however, the deployment refers to `{{ .Chart.Name }}` as the serviceaccount.
These are not guaranteed to be the same, for example, I am trying to deploy one release as `switchboard-internal` and another as `switchboard-external`, thus the deployment fails because it is looking for the `switchboard` serviceaccount.

**Comment by borchero** [comment]
Thanks for the issue! I'll likely get to it in the next 3-5 days. Also happy to accept a PR in the meantime :)
